version: '3.7'

services:

  meetings:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:10.4-alpine
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=testovoe
      - POSTGRES_PASSWORD=test
    ports:
      - "5434:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  backend: